homeassistant: 
  customize:
    lock.ok_google_attiva_allarme:
      friendly_name: "Allarme"
      icon_template: mdi:speaker-message
        
lock:
  ### lock per attivare/disattivare l'allarme HOME con Google Assistant
  ## nella configurazione di Google Assistant nel tuo configuration.yaml DEVI esporre ANCHE i lock
  ## vedi https://www.home-assistant.io/components/google_assistant/#exposed_domains
  - platform: template
    name: ok_google_attiva_allarme
    value_template: "{% if is_state('alarm_control_panel.home_alarm', 'disarmed') %}off{% else %}on{% endif %}"
    lock:
      - service: alarm_control_panel.alarm_arm_home
        data:
          entity_id: alarm_control_panel.home_alarm
    unlock:
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home_alarm

switch:
  - platform: template
    switches:
      ok_google_mo_torno:
        friendly_name: "Sospendi attivazione automatica"
        value_template: '{% if is_state("input_boolean.dss_sospesa_attivazione_automatica", "on") %}on{% else %}off{% endif %}'
        icon_template: mdi:google-home
        turn_on:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.dss_sospesa_attivazione_automatica
          # - service: script.dss_voice_riproduci_messaggio_tts
            # data:
              # message: "Ok, a dopo"
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.dss_sospesa_attivazione_automatica
            
