homeassistant: 
  customize:
    group.dss_dispositivi_user1:
      entity_picture: !secret url_immagine_profilo_user1 
    group.dss_dispositivi_user2:
      entity_picture: !secret url_immagine_profilo_user2
    group.dss_dispositivi_user1_original:
      hidden: true
    group.dss_dispositivi_user2_original:
      hidden: true
    device_tracker.pocophone_user1_ip:
      entity_picture: !secret url_immagine_profilo_user1
    device_tracker.pocophone_user1_bt:
      entity_picture: !secret url_immagine_profilo_user1
    device_tracker.mi_note_10_vale_IP:
      entity_picture: !secret url_immagine_profilo_user2
    device_tracker.mi_note_10_vale_bt:
      entity_picture: !secret url_immagine_profilo_user2
    automation.imposta_gruppo_dispositivi_tracciati:
      hidden: true
    automation.controlla_dispositivi_rimasti_a_casa_allarme_attivo_away:
      hidden: true
    automation.imposta_away_i_dispositivi_tracciati_startup:
      hidden: true
    automation.dss_alarm_automation_reimposta_gruppo_dispositivi_user1_al_rientro:
      hidden: true
    automation.dss_alarm_automation_reimposta_gruppo_dispositivi_user2_al_rientro:
      hidden: true
    script.dss_alarm_script_reimposta_gruppo_dispositivi_tracciati:
      hidden: true
    script.dss_alarm_script_rimuovi_da_gruppo_dispositivi_tracciati_rimasti_casa:
      hidden: true
    script.dss_alarm_script_attiva_reimpostazione_gruppo_dispositivi_user1_al_rientro:
      hidden: true
    script.dss_alarm_script_attiva_reimpostazione_gruppo_dispositivi_user2_al_rientro:
      hidden: true
#test di ESPHome per ESP32
    sensor.template_tracker_nut_user1:
      friendly_name: !secret nome_dispositivo_nut_tracker_user1
      entity_picture: !secret url_immagine_profilo_user1
      device_class: presence
    sensor.template_tracker_nut_user2:
      friendly_name: !secret nome_dispositivo_nut_tracker_user2
      entity_picture: !secret url_immagine_profilo_user2
      device_class: presence
#dss_mqtt_binary_sensor_ble_scanner per ESP32
    sensor.tracker_nut_user1:
      friendly_name: !secret nome_dispositivo_nut_tracker_user1
      entity_picture: !secret url_immagine_profilo_user1
    sensor.tracker_nut_user2:
      friendly_name: !secret nome_dispositivo_nut_tracker_user2
      entity_picture: !secret url_immagine_profilo_user2

# person:
  # - name: !secret nome_gruppo_dispositivi_utente1
    # id: dss_person_utente1
    # device_trackers: !secret elenco_dispositivi_tracciati_user1
    
    
    
group:
### Elenco dei Dispositivi Tracciati - inserite qui i dispositivi che fanno attivare/disattivare l'allarme in automatico ###
### io uso NMAP https://www.home-assistant.io/components/device_tracker.nmap_tracker/ ###
### e BLUETOOTH https://www.home-assistant.io/components/device_tracker.bluetooth_tracker/ ###
### Ho aggiunto anche un tracker BTLE con un ESP32. qui la mia guida: https://github.com/sdesalve/dss_mqtt_binary_sensor_ble_scanner/blob/master/guida%20MQTT.pdf

#questo gruppo viene ripopolato automaticamente con i dispositivi dei gruppi dss_dispositivi_user1 e dss_dispositivi_user2 all'avvio di HA ed ad ogni disattivazione dell'allarme dallo script dss_alarm_script_reimposta_gruppo_dispositivi_tracciati
  dss_dispositivi_tracciati:
    name: "Dispositivi Tracciati"
    entities:
      - group.dss_dispositivi_user1
      - group.dss_dispositivi_user2
      # - group.dss_dispositivi_user3
      # - group.dss_dispositivi_user4
      # comunque si possono inserire anche dispositivi singoli.
      # - device_tracker.redmi 
      # - device_tracker.00xxxxxx840

  dss_dispositivi_user1:
    name: !secret nome_gruppo_dispositivi_utente1
    entities: !secret elenco_dispositivi_tracciati_user1

  dss_dispositivi_user2:
    name: !secret nome_gruppo_dispositivi_utente2
    entities: !secret elenco_dispositivi_tracciati_user2

  # dss_dispositivi_user3:
    # name: !secret nome_gruppo_dispositivi_utente3
    # entities: !secret elenco_dispositivi_tracciati_user3

  # dss_dispositivi_user4:
    # name: !secret nome_gruppo_dispositivi_utente4
    # entities: !secret elenco_dispositivi_tracciati_user4

  dss_dispositivi_user1_original:
    entities: !secret elenco_dispositivi_tracciati_user1
    all: true
    
  dss_dispositivi_user2_original:
    entities: !secret elenco_dispositivi_tracciati_user2
    all: true


# device_tracker:
  # - platform: mqtt
    # source_type: bluetooth_le
    # qos: 1
    # devices:
      # tracker_nut_user1: !secret topic_dispositivo_nut_tracker_user1
      # tracker_nut_user2: !secret topic_dispositivo_nut_tracker_user2

sensor:

### per ovviare al problema del mancato tracciamento dei sensori di ESPHome che vengono visti come binary_sensor e non come device_tracker ho creato questi template sensori
### dovranno essere tracciati nei gruppi questi sensori (sensor.template_tracker_nut_user1 e sensor.template_tracker_nut_user2)
  - platform: template
    sensors:
      template_tracker_nut_user1:
        value_template: >-
          {% if is_state('binary_sensor.esphome_tracker_nut_user1','on') %}
          home
          {% else %}
          away
          {% endif %}
      template_tracker_nut_user2:
        value_template: >-
          {% if is_state('binary_sensor.esphome_tracker_nut_user2','on') %}
          home
          {% else %}
          away
          {% endif %}
          
### questi sono i sensori che vengono aggiornati tramite MQTT con un ESP32 e servono a rilevare le presenze con Bluetooth LowEnergy
### qui la mia guida: https://github.com/sdesalve/Open-Home-Automation/blob/master/ha_mqtt_binary_sensor_ble_scanner/guida%20MQTT.pdf

### se non usi quel sistema.... puoi rimuovere tutta questa parte
  - platform: mqtt
    name: tracker_nut_user1
    state_topic: !secret topic_dispositivo_nut_tracker_user1
    availability_topic: !secret topic_dispositivo_ESP32_availability
    expire_after: 300
    value_template: >-
      {% if value == 'ON' %}
        home
      {% elif value == 'OFF' %}
        away
      {% else %}
        away
      {% endif %}

  - platform: mqtt
    name: rssi_nut_user1
    state_topic: !secret rssi_dispositivo_nut_tracker_user1
    availability_topic: !secret topic_dispositivo_ESP32_availability
    expire_after: 300

  - platform: mqtt
    name: tracker_nut_user2
    state_topic: !secret topic_dispositivo_nut_tracker_user2
    availability_topic: !secret topic_dispositivo_ESP32_availability
    expire_after: 300
    value_template: >-
      {% if value == 'ON' %}
        home
      {% elif value == 'OFF' %}
        away
      {% else %}
        away
      {% endif %}

  - platform: mqtt
    name: rssi_nut_user2
    state_topic: !secret rssi_dispositivo_nut_tracker_user2
    availability_topic: !secret topic_dispositivo_ESP32_availability
    expire_after: 300

automation:
  - alias: dss_alarm_automation_reimposta_gruppo_dispositivi_user1_al_rientro
    initial_state: false
    trigger:
      - platform: state
        entity_id: group.dss_dispositivi_user1_original
        from: 'not_home'
        to: 'home'
    action:
      - service: group.set
        data_template:
          object_id: dss_dispositivi_user1
          entities: >-
            {% macro elenca_device_utente() %}
              {% for tracker in expand('group.dss_dispositivi_user1_original') %}
                {{ tracker.entity_id }}{% if not loop.last %}, {% endif -%}
              {% endfor %}              
            {% endmacro %}
            {{ elenca_device_utente() }}
      - service: automation.turn_off
        entity_id: automation.dss_alarm_automation_reimposta_gruppo_dispositivi_user1_al_rientro

  - alias: dss_alarm_automation_reimposta_gruppo_dispositivi_user2_al_rientro
    initial_state: false
    trigger:
      - platform: state
        entity_id: group.dss_dispositivi_user2_original
        from: 'not_home'
        to: 'home'
    action:
      - service: group.set
        data_template:
          object_id: dss_dispositivi_user2
          entities: >-
            {% macro elenca_device_utente() %}
              {% for tracker in expand('group.dss_dispositivi_user2_original') %}
                {{ tracker.entity_id }}{% if not loop.last %}, {% endif -%}
              {% endfor %}              
            {% endmacro %}
            {{ elenca_device_utente() }}
      - service: automation.turn_off
        entity_id: automation.dss_alarm_automation_reimposta_gruppo_dispositivi_user2_al_rientro

  - alias: "Imposta away i dispositivi tracciati startup"
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: mqtt.publish
        data_template:
          topic: !secret topic_dispositivo_ESP32_availability
          payload: 'OFF'
      - service: mqtt.publish
        data_template:
          topic: !secret topic_dispositivo_nut_tracker_user1
          payload: 'OFF'
      - service: mqtt.publish
        data_template:
          topic: !secret topic_dispositivo_nut_tracker_user2
          payload: 'OFF'
        
  - alias: "Imposta gruppo dispositivi tracciati"
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: 'disarmed'
    action:
      - service: script.dss_alarm_script_reimposta_gruppo_dispositivi_tracciati
      
  - alias: "Controlla dispositivi rimasti a casa allarme attivo AWAY"
    initial_state: true
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: 'armed_away'
        for: '00:03:00'
    action:
      - condition: template
        value_template: >-
          {%- macro controllo_device() -%}
            {%- for tracker in expand('group.dss_dispositivi_user1', 'group.dss_dispositivi_user2') if tracker.state == 'home' -%} 
              {{ tracker.entity_id }}{% if not loop.last %}, {% endif -%}
            {%- endfor -%}
          {%- endmacro -%}
          {{ controllo_device() | trim != "" }}
      - service: script.dss_alarm_script_rimuovi_da_gruppo_dispositivi_tracciati_rimasti_casa
      - service: script.dss_alarm_script_invia_notifiche
        data_template:
          message: >-
            {% macro controllo_device() %}
              {% for tracker in expand('group.dss_dispositivi_user1', 'group.dss_dispositivi_user2') if tracker.state == 'home' -%} 
            
            
                ⭐️ {{ tracker.name }}
              {% endfor %}              
            {% endmacro %}
            ATTENZIONE: i seguenti dispositivi tracciati sono rimasti a casa e li ho rimossi dai dispositivi tracciati:
            {{ controllo_device() }}
      - service: script.dss_alarm_script_attiva_reimpostazione_gruppo_dispositivi_user1_al_rientro
      - service: script.dss_alarm_script_attiva_reimpostazione_gruppo_dispositivi_user2_al_rientro

script:
  dss_alarm_script_attiva_reimpostazione_gruppo_dispositivi_user1_al_rientro:
    sequence:
      - condition: template
        value_template: >
          {% macro controllo_device() %}
            {% for tracker in expand('group.dss_dispositivi_user1') if tracker.state == 'home' -%} 
              {{ tracker.entity_id }}{% if not loop.last %}, {% endif -%}
            {% endfor %}              
          {% endmacro %}
          {{ controllo_device() | trim != "" }}
      - service: automation.turn_on
        entity_id: automation.dss_alarm_automation_reimposta_gruppo_dispositivi_user1_al_rientro
    
  dss_alarm_script_attiva_reimpostazione_gruppo_dispositivi_user2_al_rientro:
    sequence:
      - condition: template
        value_template: >
          {% macro controllo_device() %}
            {% for tracker in expand('group.dss_dispositivi_user2') if tracker.state == 'home' -%} 
              {{ tracker.entity_id }}{% if not loop.last %}, {% endif -%}
            {% endfor %}              
          {% endmacro %}
          {{ controllo_device() | trim != "" }}
      - service: automation.turn_on
        entity_id: automation.dss_alarm_automation_reimposta_gruppo_dispositivi_user2_al_rientro
    
  dss_alarm_script_reimposta_gruppo_dispositivi_tracciati:
    sequence:
      # - service: group.reload
      # - service: group.set
        # data_template:
          # object_id: dss_dispositivi_tracciati
          # entities: 
            # - group.dss_dispositivi_user1
            # - group.dss_dispositivi_user2
      - service: group.set
        data_template:
          object_id: dss_dispositivi_tracciati
          entities: >-
            {% macro controllo_device() %}
              {% for tracker in expand('group.dss_dispositivi_user1', 'group.dss_dispositivi_user2') %}
                {{ tracker.entity_id }}{% if not loop.last %}, {% endif -%}
              {% endfor %}              
            {% endmacro %}
            {{ controllo_device() }}

  dss_alarm_script_rimuovi_da_gruppo_dispositivi_tracciati_rimasti_casa:
    sequence:
      - service: group.set
        data_template:
          object_id: dss_dispositivi_tracciati
          entities: >-
            {% macro controllo_device() %}
              {% for tracker in expand('group.dss_dispositivi_user1', 'group.dss_dispositivi_user2') if tracker.state != 'home' -%} 
                {{ tracker.entity_id }}{% if not loop.last %}, {% endif -%}
              {% endfor %}              
            {% endmacro %}
            {{ controllo_device() }}
      - service: group.set
        data_template:
          object_id: dss_dispositivi_user1
          entities: >-
            {% macro controllo_device() %}
              {% for tracker in expand('group.dss_dispositivi_user1') if tracker.state != 'home' -%} 
                {{ tracker.entity_id }}{% if not loop.last %}, {% endif -%}
              {% endfor %}              
            {% endmacro %}
            {{ controllo_device() }}
      - service: group.set
        data_template:
          object_id: dss_dispositivi_user2
          entities: >-
            {% macro controllo_device() %}
              {% for tracker in expand('group.dss_dispositivi_user2') if tracker.state != 'home' -%} 
                {{ tracker.entity_id }}{% if not loop.last %}, {% endif -%}
              {% endfor %}              
            {% endmacro %}
            {{ controllo_device() }}

# input_select:
  # dss_binary_sensor_secrets_dispositivi_tracciati_non_ignorare_rimasti_casa:
    # options: !secret dss_binary_sensor_secrets_dispositivi_tracciati_non_ignorare_rimasti_casa

  # dss_binary_sensor_secrets_dispositivi_tracciati_da_ignorare_rimasti_casa:
    # options: ['nessuno']
