smartir:

binary_sensor:
  - name: chromecast_cucina_ping 
    platform: ping
    host: !secret chromecast_cucina_ip
    count: 2
    scan_interval: 5
    
  - name: chromecast_letto_ping 
    platform: ping
    host: !secret chromecast_letto_ip
    count: 2
    scan_interval: 5

  - name: chromecast_salotto_ping 
    platform: ping
    host: !secret tv_hitachi_salotto_ip
    count: 2
    scan_interval: 5

media_player:
  - platform: smartir
    name: TV Cucina
    unique_id: tv_cucina_smartir
    device_code: 1060
    controller_data: !secret broadlink_rm_cucina_ip
    power_sensor: binary_sensor.chromecast_cucina_ping
    
  - platform: smartir
    name: TV Letto
    unique_id: tv_letto_smartir
    device_code: 1060
    controller_data: !secret broadlink_rm_letto_ip
    power_sensor: binary_sensor.chromecast_letto_ping
    
  - platform: smartir
    name: TV Salotto
    unique_id: tv_salotto_smartir
    device_code: 3482
    controller_data: !secret broadlink_rm_salotto_ip
    power_sensor: binary_sensor.chromecast_salotto_ping
    

climate:
  - platform: smartir
    name: 'Fujitsu Cucina'
    unique_id: fujitsu_cucina
    device_code: 3482
    controller_data: !secret broadlink_rm_cucina_ip
    temperature_sensor: !secret entity_temperature_cucina
    humidity_sensor: !secret entity_humidity_cucina
    power_sensor: !secret entity_sensore_fujitsu_cucina

  - platform: smartir
    name: 'Fujitsu Letto'
    unique_id: fujitsu_letto
    device_code: 3482
    controller_data: !secret broadlink_rm_letto_ip
    temperature_sensor: !secret entity_temperature_letto
    humidity_sensor: !secret entity_humidity_letto
    power_sensor: !secret entity_sensore_fujitsu_letto

switch:
  - platform: broadlink
    friendly_name: Broadlink Switch Cucina
    host: !secret broadlink_rm_cucina_ip
    mac: !secret broadlink_rm_cucina_mac
    type: rm
    # timeout: 30
    # switches:
      # learner_cucina:
        # friendly_name: "Learner Cucina"
        # command_on: ''
        # command_off: ''
    
  - platform: broadlink
    friendly_name: Broadlink Switch Letto
    host: !secret broadlink_rm_letto_ip
    mac: !secret broadlink_rm_letto_mac
    type: rm
    # timeout: 30
    # switches:
      # learner_letto:
        # friendly_name: "Learner Letto"
        # command_on: ''
        # command_off: ''
        
  - platform: broadlink
    friendly_name: Broadlink Switch Salotto
    host: !secret broadlink_rm_salotto_ip
    mac: !secret broadlink_rm_salotto_mac
    type: rm
    timeout: 30
    switches:
      learner_salotto:
        friendly_name: "Learner Salotto"
        command_on: ''
        command_off: ''
